### ISSUE TITLE
Filters not being applied

### ISSUE THREAD

**Issue by jlunamx86** [microsoft/PowerBI-Tools-For-Capacities#13]
I'm able to run this tool. However, it seems filters are not being applied, no error is shown

In my PBIReport.JSON I can see:

`reportParameters='{"reportUrl":"https://app.powerbi.com/reportEmbed?reportId=XXXXXX&groupId=XXXXXXX&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVBBQVMtMS1TQ1VTLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0IiwiZW1iZWRGZWF0dXJlcyI6eyJtb2Rlcm5FbWJlZCI6ZmFsc2V9fQ%3d%3d","filterStart":201901,"filterMax":201912,"sessionRestart":100,"filterTable":"cub vwPeriod","filterColumn":"AX_MONTH_SHORT"}';`

which make sense to me.

Fact table is of course related to 'cub vwPeriod' table but the report iterate over and over again on the same period "201912" I see no changes when running on browsers

any idea?

**Comment by furmangg** [comment]
Are you using the RealisticLoadTestTool or the worst case scenario one?

**Comment by jlunamx86** [comment]
Hi there, I use "worst case scenario" last version

**Comment by jlunamx86** [comment]
Apologies, I found a wrong field name in my code. Thanks
