### ISSUE TITLE
Receiving parse errors while executing the Initiate_Load Powershell

### ISSUE THREAD

**Issue by darpang** [microsoft/PowerBI-Tools-For-Capacities#18]
I am receiving parse errors as below, while executing .\Initiate_Load.ps1 of LoadTestingPowerShellTool . Please find below the image. Kindly help.

<img width="614" alt="parse error" src="https://user-images.githubusercontent.com/8443487/95937149-fa8b9900-0d8b-11eb-8023-281d974a0c52.png">

**Comment by furmangg** [comment]
Can you confirm that .ps1 script file contents matches https://raw.githubusercontent.com/microsoft/PowerBI-Tools-For-Capacities/master/LoadTestingPowerShellTool/Initiate_Load.ps1

I’m worried you downloaded the HTML wrapper page instead of just the .ps1.

**Comment by darpang** [comment]
Yes, thanks. That solved the issue!
